image: python:3.10-slim-buster

stages:
  - test

test:
  script:
    - python -V
    - pip install poetry
    - poetry install
    - pre-commit run -a --hook-stage=push
  artifacts:
    expire_in: 30 days
    when: always
    paths:
      - coverage.xml
    reports:
      junit: report.xml
